### ISSUE TITLE
IndexOutOfBoundsException upon connection

### ISSUE THREAD

**Issue by ap3h3ad** [OpenIdentityPlatform/OpenDJ#12]
**Describe the bug**
On every attempt to connect to the OpenDJ server (4.1.10.) we get an ArrayOutOfBoundsException. This applys especially to dsconfig. Even only using dsconfig without any further arguments results in the error (after following the instructions under "How-to build" and "How-to run after build").

**To Reproduce**
1. Deploy the actual version
2. Start the install routine
3. Use the command dsconfig

**Expected behavior**
It should throw the given error:

```
[30/Jul/2018:14:57:04 +0200] category=PROTOCOL severity=NOTICE msgID=276 msg=Started listening for new connections on LDAP Connection Handler 0.0.0.0 port 389
java.lang.IndexOutOfBoundsException: index 0
	at java.util.concurrent.atomic.AtomicReferenceArray.checkedByteOffset(AtomicReferenceArray.java:78)
	at java.util.concurrent.atomic.AtomicReferenceArray.compareAndSet(AtomicReferenceArray.java:178)
	at org.glassfish.grizzly.memory.PooledMemoryManager$PoolSlice.offer(PooledMemoryManager.java:723)
	at org.glassfish.grizzly.memory.PooledMemoryManager$PoolByteBufferWrapper.returnToPool(PooledMemoryManager.java:1299)
	at org.glassfish.grizzly.memory.PooledMemoryManager$PoolByteBufferWrapper.dispose0(PooledMemoryManager.java:1258)
	at org.glassfish.grizzly.memory.PooledMemoryManager$PoolByteBufferWrapper.dispose(PooledMemoryManager.java:1240)
	at org.glassfish.grizzly.memory.ByteBufferWrapper.tryDispose(ByteBufferWrapper.java:125)
	at org.forgerock.opendj.grizzly.ASN1BufferReader.close(ASN1BufferReader.java:165)
	at org.forgerock.util.Utils.closeSilently(Utils.java:56)
	at org.forgerock.util.Utils.closeSilently(Utils.java:40)
	at org.forgerock.opendj.reactive.LDAPClientConnection2$3.subscribe(LDAPClientConnection2.java:971)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:72)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at org.forgerock.opendj.reactive.LDAPClientConnection2$BlockingBackpressureSubscription.subscribe(LDAPClientConnection2.java:1707)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:47)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:36)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at com.forgerock.reactive.RxJavaStreams$RxJavaStream.subscribe(RxJavaStreams.java:202)
	at org.forgerock.opendj.grizzly.LDAPServerFilter$ClientConnectionImpl$2.subscribe(LDAPServerFilter.java:374)
	at com.forgerock.reactive.RxJavaStreams$2.subscribe(RxJavaStreams.java:167)
	at io.reactivex.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:39)
	at io.reactivex.Completable.subscribe(Completable.java:1497)
	at io.reactivex.internal.operators.completable.CompletableResumeNext.subscribeActual(CompletableResumeNext.java:41)
	at io.reactivex.Completable.subscribe(Completable.java:1497)
	at io.reactivex.internal.operators.completable.CompletableToFlowable.subscribeActual(CompletableToFlowable.java:32)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at com.forgerock.reactive.RxJavaStreams$RxJavaCompletable.subscribe(RxJavaStreams.java:353)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:156)
	at org.forgerock.opendj.grizzly.LDAPServerFilter$ClientConnectionImpl$GrizzlyBackpressureSubscription.handleRead(LDAPServerFilter.java:270)
	at org.forgerock.opendj.grizzly.LDAPServerFilter$ClientConnectionImpl.handleRead(LDAPServerFilter.java:319)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:103)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:415)
	at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:384)
	at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:348)
	at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:279)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
```

**Desktop (please complete the following information):**
 - CentOS
 - 7.5.1804

**Additional context**
The sleepycat depency (7.5.11.) cannot be resolved by maven. Since the 7.5.11.jar can't be found anywhere we changed the version to the one we already have built. Could this be a problem?

**Comment by vharseko** [comment]
The sleepycat depency (7.5.11.) resolved from 
``` xml
  <repositories>
    <repository>
      <id>oracle-repository</id>
      <name>Oracle Maven Repository</name>
      <url>http://download.oracle.com/maven</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
  </repositories>
```
defined in OpenDJ/opendj-server-legacy/pom.xml
