### ISSUE TITLE
opendj-embedded-server  run  error 

### ISSUE THREAD

**Issue by Link-Kou** [OpenIdentityPlatform/OpenDJ#153]
```java

public static void main(String[] args) throws EmbeddedDirectoryServerException {
        final String tmpdir = "/Users/lk/Downloads";
        performSetup(tmpdir, 33588, 33589);
    }

    static void performSetup(final String serverRootDir, final int ldapPort, final int adminPort) throws EmbeddedDirectoryServerException {
        EmbeddedDirectoryServer server =
                manageEmbeddedDirectoryServer(
                        configParams()
                                .serverRootDirectory(serverRootDir)
                                .configurationFile(serverRootDir + File.separator + "config/config.ldif"),
                        connectionParams()
                                .hostName("localhost")
                                .ldapPort(ldapPort)
                                .bindDn("cn=Directory Manager")
                                .bindPassword("password")
                                .adminPort(adminPort),
                        System.out,
                        System.err);
        server.start();
        while (true) {
            System.out.println(123);
        }
    }



```

### **ERROR**

Exception in thread "main" org.forgerock.opendj.server.embedded.EmbeddedDirectoryServerException: An error occurred while attempting to start the embedded server with server root '/Users/lk/Downloads' : InitializationException: Unable to load the configuration-enabled schema: FileNotFoundException: 02-config.ldif (No such file or directory) (FileInputStream.java:-2 FileInputStream.java:195 FileInputStream.java:138 FileReader.java:72 ConfigurationHandler.java:1222 ConfigurationHandler.java:217 ConfigurationHandler.java:199 DirectoryServer.java:1288 DirectoryServer.java:4409 EmbeddedDirectoryServer.java:520 LdapBootstrap.java:38 LdapBootstrap.java:21) (ConfigurationHandler.java:1232 ConfigurationHandler.java:217 ConfigurationHandler.java:199 DirectoryServer.java:1288 DirectoryServer.java:4409 EmbeddedDirectoryServer.java:520 LdapBootstrap.java:38 LdapBootstrap.java:21)
	at org.forgerock.opendj.server.embedded.EmbeddedDirectoryServer.start(EmbeddedDirectoryServer.java:525)
	at org.example.LdapBootstrap.performSetup(LdapBootstrap.java:38)
	at org.example.LdapBootstrap.main(LdapBootstrap.java:21)

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "Directory Server Shutdown Hook"

**Comment by vharseko** [comment]
```
package ru.org.openam.embedded.opendj;

import java.io.Closeable;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import static org.forgerock.opendj.server.embedded.ConfigParameters.configParams;
import static org.forgerock.opendj.server.embedded.ConnectionParameters.connectionParams;
import static org.forgerock.opendj.server.embedded.EmbeddedDirectoryServer.*;
import static org.forgerock.opendj.server.embedded.SetupParameters.setupParams;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.forgerock.i18n.LocalizableMessage;
import org.forgerock.opendj.config.client.ManagementContext;
import org.forgerock.opendj.ldap.DN;
import org.forgerock.opendj.ldap.ResultCode;
import org.forgerock.opendj.ldap.SearchScope;
import org.forgerock.opendj.ldap.responses.SearchResultEntry;
import org.forgerock.opendj.ldif.ConnectionEntryReader;
import org.forgerock.opendj.ldif.LDIFEntryWriter;
import org.forgerock.opendj.server.config.client.BackendCfgClient;
import org.forgerock.opendj.server.embedded.EmbeddedDirectoryServer;
import org.opends.server.backends.MemoryBackend;
import org.opends.server.protocols.internal.InternalClientConnection;
import org.opends.server.types.Entry;
import org.opends.server.types.LDIFImportConfig;
import org.opends.server.util.LDIFReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Server implements Runnable, Closeable{
	final static Logger logger = LoggerFactory.getLogger(Server.class);
	
	private static final String JAR_SCHEMA_DIRECTORY = "opendj/config/schema/";
	
	EmbeddedDirectoryServer server;
	
	public Server() {
		if (System.getProperty(Server.class.getPackage().getName()+".ldif.data")!=null) {
			File tempDirectory = new File(System.getProperty("java.io.tmpdir"));
			File rootDirectory = new File(tempDirectory, "opendj");
			try {
				if(rootDirectory.exists())
					FileUtils.deleteDirectory(rootDirectory);
				rootDirectory.mkdir();
		    		
				File configDirectory = new File(rootDirectory, "config");
				File schemaDirectory = new File(configDirectory, "schema");
				server = manageEmbeddedDirectoryServer(
			                        configParams()
				                        		.serverRootDirectory(rootDirectory.getPath())
				                        		.configurationFile(Paths.get(rootDirectory.getPath(), "config", "config.ldif").toString()),
			                        connectionParams()
				                            .hostName("localhost")
				                            .ldapPort(Integer.parseInt(System.getProperty(Server.class.getPackage().getName()+".port","1389")))
				                            .adminPort(Integer.parseInt(System.getProperty(Server.class.getPackage().getName()+".admin_port","4444")))
				                            .bindDn("cn=Directory Manager")
				                            .bindPassword(System.getProperty(Server.class.getPackage().getName()+".password","amAdminamAdmin")),
			                            System.out,
			                            System.err);
				
				copyFilesFromJar(new String[] {"opendj.zip"},"embedded-opendj/",rootDirectory);
				server.extractArchiveForSetup(new File(rootDirectory,"opendj.zip"));
				
				server.setup(
		                setupParams()
		                    .baseDn(System.getProperty(Server.class.getPackage().getName()+".root", "dc=amroot"))
		                    .backendType(System.getProperty(Server.class.getPackage().getName()+".backend", "je"))
		                    .jmxPort(Integer.parseInt(System.getProperty(Server.class.getPackage().getName()+".jmx_port","1689")))
		                    );
				
				String[] schemaFiles = {};
				if (System.getProperty(Server.class.getPackage().getName()+".ldif.schema")!=null)
					schemaFiles=append(schemaFiles, System.getProperty(Server.class.getPackage().getName()+".ldif.schema"));
				else
					schemaFiles=append(schemaFiles, "99-user.ldif");
				copyFilesFromJar(schemaFiles, JAR_SCHEMA_DIRECTORY, schemaDirectory);	
				
			}catch (Exception e) {
				throw new RuntimeException(e);
			}
			 Runtime.getRuntime().addShutdownHook(new Thread() {
		            @Override
		            public void run() {
	        				close();
		            }
		        });
		}
	}
	
	static final ScheduledExecutorService cron = Executors.newScheduledThreadPool(1);
	public void run() {
		if (System.getProperty(Server.class.getPackage().getName()+".ldif.data")==null) {
			logger.info("Embedded OpenDJ ldif.data  not set");
			return;
		}
		LDIFImportConfig importConfig=null;
		try {
			final DN baseDN = DN.valueOf(System.getProperty(Server.class.getPackage().getName()+".root", "dc=amroot"));
			try  {
				ManagementContext config = server.getConfiguration();
	            BackendCfgClient userRoot = config.getRootConfiguration().getBackend("userRoot");
	            userRoot.setBaseDN((Arrays.asList(new DN[] { baseDN })));
	            userRoot.setEnabled(true);
	            userRoot.commit();
	            config.close();
	        } catch (Exception e) {
	            throw new RuntimeException(e);
	        }
			
			logger.info("Start OpenDJ ...");
			server.start();
			
			final String file=System.getProperty(Server.class.getPackage().getName()+".ldif.data","/opendj/test.ldif");
			importConfig =new LDIFImportConfig(new File(file).exists()?new FileInputStream(file):Server.class.getResourceAsStream(file));
		    //importConfig.setAppendToExistingData(true);
			//importConfig.setReplaceExistingEntries(true);
			importConfig.setCompressed(false);
			importConfig.setEncrypted(false);
			importConfig.setValidateSchema(false);
			//importConfig.setSkipDNValidation(false);
			LDIFReader reader=new LDIFReader(importConfig);
			Entry  entryBefore;
			InternalClientConnection connection =InternalClientConnection.getRootConnection();
			while ((entryBefore = reader.readEntry(false)) != null) {
				ResultCode rc=connection.processAdd(entryBefore).getResultCode();
				if (rc.isExceptional())
					logger.error("import ldif : {} {} {}",entryBefore.getName(),rc,rc.getName());
				else
					logger.info("import ldif : {} {}",entryBefore.getName(),rc);
			}
			reader.close();
			
			//set save
			if (new File(file).exists())
				cron.scheduleAtFixedRate(new Runnable() {
					public void run() {
						try{
							String tempFile= File.createTempFile("temp", Long.toString(System.nanoTime())).getPath();
							//indexes
							FileOutputStream fos=new FileOutputStream(tempFile, false);
							LDIFEntryWriter LDIFwriter=new LDIFEntryWriter(fos);
							ConnectionEntryReader reader=server.getInternalConnection().search("cn=Backends,cn=config",SearchScope.WHOLE_SUBTREE,"(objectClass=ds-cfg-backend-index)");
							while(reader.hasNext()) 
								if (!reader.isReference()) {
									SearchResultEntry se=reader.readEntry();
									if (!skipEntry(se)) {
										LDIFwriter.writeEntry(se);
										logger.trace("export {}",se.toString());
									}
								}
							reader.close();
							//data
							reader=server.getInternalConnection().search(baseDN.toString(),SearchScope.WHOLE_SUBTREE,"(objectClass=*)");
							while(reader.hasNext()) 
								if (!reader.isReference()) {
									SearchResultEntry se=reader.readEntry();
									if (!skipEntry(se)) {
										LDIFwriter.writeEntry(se);
										logger.trace("export {}",se.toString());
									}
								}
							reader.close();
							LDIFwriter.close();
							fos.close();
							Files.move(new File(tempFile).toPath(), new File(file).toPath(),StandardCopyOption.REPLACE_EXISTING);
							logger.debug("export LDIF {}",file);
						}catch(Throwable e){
							logger.error("export LDIF",e);
						}
					}
				},30, 15, TimeUnit.SECONDS);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}finally {
			if(importConfig!=null)
				importConfig.close();
		}
	}
	
	static Set<String> skipSet=new HashSet<String>();
	static {
		skipSet.addAll(Arrays.asList(System.getProperty(Server.class.getPackage().getName()+".skip", ",ou=famrecords,;,ou=sample-skip-group,").toLowerCase().split(";")));
	}
	
	//skip entry
	boolean skipEntry(SearchResultEntry se) {
		for (String skip : skipSet) {
			if (se.getName().toString().toLowerCase().contains(skip)){
				logger.trace("ignore export {}",se.toString());
				return true;
			}
		}
		return false;
	}
	
	public void close()  {
		if (server.isRunning())
			try {
				logger.info("Shutting down OpenDJ ...");
		        server.stop(Server.class.getName(),LocalizableMessage.raw("Stopped after receiving Control-C"));
			}catch (Throwable e) {
				;
			}
	}
	
	static <T> T[] append(T[] arr, T element) {
	    final int N = arr.length;
	    arr = Arrays.copyOf(arr, N + 1);
	    arr[N] = element;
	    return arr;
	}
	
	static void copyFilesFromJar(String[] jarFiles, String jarDirectory, File outputDirectory) throws IOException
	{
		for(String jarFile : jarFiles)
		{
			File outputFile = new File(outputDirectory, new File(jarFile).getName());
			final String resourcePatch=(!jarFile.contains("/"))? "/"+jarDirectory + jarFile:jarFile;
			InputStream in = new File(jarFile).exists()?new FileInputStream(new File(jarFile)):MemoryBackend.class.getResourceAsStream(resourcePatch); 
			if (in==null)
				throw new IOException("cannot find "+resourcePatch);
			FileUtils.copyInputStreamToFile(in, outputFile);
			in.close();
		}
	}
	
	static public void main(String [] params) throws Exception   {
		Server s=new Server();
		s.run();
		s.close();
	}
}
```

**Comment by Link-Kou** [comment]
@vharseko  

```java

if (System.getProperty(Server.class.getPackage().getName()+".ldif.data")!=null) {

```

How to configure  ldif.data ？

**Comment by Link-Kou** [comment]
@vharseko  

Where can I get the required files

![image](https://user-images.githubusercontent.com/22113151/104152729-6200c580-541b-11eb-9ec6-7eaa7bc46ca0.png)

**Comment by vharseko** [comment]
> @vharseko
> 
> Where can I get the required files
> 
https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/4.4.9/opendj-4.4.9.zip
