### ISSUE TITLE
Unable to administer Local Server with control-panel

### ISSUE THREAD

**Issue by nightah** [OpenIdentityPlatform/OpenDJ#16]
**Describe the bug**
As of the latest update I am unable to administer my server using the Local Server option via the control-panel application within the Docker container.

**To Reproduce**
1. Launch control-panel
2. Fill in Bind DN and Password
3. Click OK

```
Error reading the configuration file.
This could be caused because there is not an enabled LDAP port for the specified connection parameters or because you do not have read rights on the configuration file.
```

**Expected behavior**
The control-panel to launch, providing the ability to administer the local server.

**Screenshots**
https://nerv.cx/3kzSw

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
I'm not entirely sure if this is related to #13 or the fix https://github.com/OpenIdentityPlatform/OpenDJ/commit/b8515346374967f499c3ef9185dafaff72171ebe.
It also seems that if I try to administer this server as a Remote Server that it doesn't pick up any of my schema changes, for example I have added another objectClass to some users and if I try to manage those entries they do not show up appropriately and the following error is thrown:

```
Exception in thread "AWT-EventQueue-0" org.forgerock.opendj.ldap.schema.UnknownSchemaElementException: No object class with name or OID "whitelistedPerson" exists in the schema
        at org.forgerock.opendj.ldap.schema.Schema$StrictImpl.getObjectClass(Schema.java:603)
        at org.forgerock.opendj.ldap.schema.Schema.getObjectClass(Schema.java:1227)
        at org.opends.guitools.controlpanel.ui.BrowseEntriesPanel.hasUserPassword(BrowseEntriesPanel.java:463)
        at org.opends.guitools.controlpanel.ui.BrowseEntriesPanel.access$1200(BrowseEntriesPanel.java:89)
        at org.opends.guitools.controlpanel.ui.BrowseEntriesPanel$1.valueChanged(BrowseEntriesPanel.java:306)
        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
        at javax.swing.JTree.setSelectionPath(JTree.java:1634)
        at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
        at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
        at java.awt.Component.processMouseEvent(Component.java:6530)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Happy to lodge this as a separate issue if required.

**Comment by maximthomas** [comment]
@nightah could you porvide more details, how do you launch control panel within OpenDJ running in Docker container?

**Comment by nightah** [comment]
@maximthomas: I have X11 forwarding on my host and I bind mount in `/opt/opendj` from said host.

`docker run --net=host -e DISPLAY=$DISPLAY -v "$HOME/.Xauthority:/root/.Xauthority:rw" -v "/srv/docker/.ldap:/opt/opendj" openidentityplatform/opendj /opt/opendj/bin/control-panel`

This worked previously with version 4.1.10.

**Comment by vharseko** [comment]
rollback https://github.com/OpenIdentityPlatform/OpenDJ/commit/b4d3ffb7b344301c97bb5c31ec1fa0e10628b85a

**Comment by vharseko** [comment]
please check in https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.2.2 :
- administer my server using the Local Server option
- try to administer this server as a Remote Server that it doesn't pick up any of my schema changes

**Comment by nightah** [comment]
@vharseko: Confirmed both issues now appear to be resolved.

I can administer via the Local Server now and I can see schema changes that have been made when connecting via the Remote Server option.

Just to clarify though I've only tested reading at this point, I haven't actually attempted to try to change anything, so when I do some more testing I'll report back if I find any other issues.

**Comment by devdkp** [comment]
> please check in https://github.com/OpenIdentityPlatform/OpenDJ/releases/tag/4.2.2 :
> 
> * administer my server using the Local Server option
> * try to administer this server as a Remote Server that it doesn't pick up any of my schema changes

Yes this is working fine on local as well as remote server

**Comment by imShakil** [comment]
I had to installed default-jre instead of default-jre-headless to run control panel.
OS: ubuntu 22
OpenDJ: 4.6.5
