### ISSUE TITLE
4.4.11 docker image attempts to downgrade

### ISSUE THREAD

**Issue by nightah** [OpenIdentityPlatform/OpenDJ#173]
**Describe the bug**

**To Reproduce**
1. Have OpenDJ deployed via Docker with v4.4.10
2. Update container to v4.4.11 and watch the upgrade execute upon startup
3. See error:
```
>>>> OpenDJ Upgrade Utility 

 * OpenDJ will be upgraded from version 
 4.4.10.d0766ccc36a12c367b873ff00d8f96bf51fe3b17 to 
 4.4.8.a3a4d052bd33e5ddd8d79ecf7f552a1f1c47c905 
 * See '/opt/opendj/data/logs/upgrade.log' for a detailed log of this operation 

** The upgrade failed to complete for the following reason: fromKey > toKey 

[22/Jun/2021:10:59:01 +1000] category=com.forgerock.opendj.ldap.config.config severity=NOTICE msgID=571 msg=Loaded extension from file '/opt/opendj/lib/extensions/snmp-mib2605.jar' (build 4.4.8-SNAPSHOT, revision a3a4d052bd33e5ddd8d79ecf7f552a1f1c47c905) 
[22/Jun/2021:10:59:01 +1000] category=CORE severity=NOTICE msgID=139 msg=The Directory Server has sent an alert notification generated by class org.opends.server.core.DirectoryServer (alert type org.opends.server.DirectoryServerShutdown, alert ID org.opends.messages.core-141): The Directory Server has started the shutdown process. The shutdown was initiated by an instance of class org.opends.server.core.DirectoryServer and the reason provided for the shutdown was An error occurred while trying to start the Directory Server: InitializationException: The OpenDJ binary version '4.4.8.a3a4d052bd33e5ddd8d79ecf7f552a1f1c47c905' does not match the installed version '4.4.10.d0766ccc36a12c367b873ff00d8f96bf51fe3b17'. Please run upgrade before continuing (DirectoryServer.java:1327 DirectoryServer.java:5041) 
Exception in thread "main" java.lang.NullPointerException 
	at org.opends.server.core.DirectoryServer.shutDown(DirectoryServer.java:4258) 
	at org.opends.server.core.DirectoryServer.main(DirectoryServer.java:5047) 
```

**Expected behavior**
Container to attempt upgrade from v4.4.11 to v4.4.11 and successful run.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
Not applicable.

**Comment by vharseko** [comment]
refresh docker tags https://hub.docker.com/layers/openidentityplatform/opendj/4.4.11/images/sha256-4ad61c8d81e62762315a6b59c9e959be175a2937feb4650f144303fb64980592?context=explore https://hub.docker.com/layers/openidentityplatform/opendj/latest/images/sha256-4ad61c8d81e62762315a6b59c9e959be175a2937feb4650f144303fb64980592?context=explore
