### ISSUE TITLE
Error while deploying Example Plugin

### ISSUE THREAD

**Issue by 13Homer** [OpenIdentityPlatform/OpenDJ#76]
It's vanilla serwer, build without any change. After installing plugin according to README https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-server-example-plugin/README.example.plugin server refuses to start:
```
[08/Jul/2019:22:26:14 +0200] category=com.forgerock.opendj.ldap.config.config severity=NOTICE msgID=571 msg=Loaded extension from file '/home/homer/work/tmp/opendj/lib/extensions/snmp-mib2605.jar' (build 4.4.3-SNAPSHOT, revision 728eb3e9368b641832819b7c8687864a938dee4b)
[08/Jul/2019:22:26:14 +0200] category=com.forgerock.opendj.ldap.config.config severity=NOTICE msgID=571 msg=Loaded extension from file '/home/homer/work/tmp/opendj/lib/extensions/opendj-server-example-plugin-4.4.3-SNAPSHOT.jar' (build <unknown>, revision <unknown>)
[08/Jul/2019:22:26:14 +0200] category=CORE severity=NOTICE msgID=134 msg=OpenDJ Server 4.4.3-SNAPSHOT (build 20190708170926, revision number 728eb3e9368b641832819b7c8687864a938dee4b) starting up
[08/Jul/2019:22:26:15 +0200] category=JVM severity=NOTICE msgID=21 msg=Installation Directory:  /home/homer/work/tmp/opendj
[08/Jul/2019:22:26:15 +0200] category=JVM severity=NOTICE msgID=23 msg=Instance Directory:      /home/homer/work/tmp/opendj
[08/Jul/2019:22:26:15 +0200] category=JVM severity=NOTICE msgID=17 msg=JVM Information: 1.8.0_201-b09 by Oracle Corporation, 64-bit architecture, 3717201920 bytes heap size
[08/Jul/2019:22:26:15 +0200] category=JVM severity=NOTICE msgID=18 msg=JVM Host: SM-Latitude-E7440, running Linux 4.18.0-25-generic amd64, 16720707584 bytes physical memory size, number of processors available 4
[08/Jul/2019:22:26:15 +0200] category=JVM severity=NOTICE msgID=19 msg=JVM Arguments: "-Dorg.opends.server.scriptName=start-ds"
[08/Jul/2019:22:26:17 +0200] category=BACKEND severity=NOTICE msgID=513 msg=The database backend userRoot containing 2002 entries has started
[08/Jul/2019:22:26:17 +0200] category=EXTENSIONS severity=NOTICE msgID=221 msg=DIGEST-MD5 SASL mechanism using a server fully qualified domain name of: localhost
[08/Jul/2019:22:26:17 +0200] category=CORE severity=NOTICE msgID=139 msg=The Directory Server has sent an alert notification generated by class org.opends.server.core.DirectoryServer (alert type org.opends.server.DirectoryServerShutdown, alert ID org.opends.messages.core-141): The Directory Server has started the shutdown process. The shutdown was initiated by an instance of class org.opends.server.core.DirectoryServer and the reason provided for the shutdown was An error occurred while trying to start the Directory Server: MissingResourceException: Can't find resource config/profiles/ldap/com/example/opendj/meta/ExamplePluginCfgDefn.properties (ManagedObjectDefinitionResource.java:104 ManagedObjectDefinitionResource.java:77 LDAPProfile.java:268 ServerManagementContext.java:239 AbstractManagedObjectDefinition.java:924 AbstractManagedObjectDefinition.java:930 AbstractManagedObjectDefinition.java:710 ServerManagementContext.java:516 ServerManagementContext.java:479 ServerManagementContext.java:345 ServerManagedObject.java:411 PluginRootCfgDefn.java:3505 PluginConfigManager.java:317 DirectoryServer.java:1489 DirectoryServer.java:5035)
[08/Jul/2019:22:26:17 +0200] category=BACKEND severity=NOTICE msgID=370 msg=The backend userRoot is now taken offline
[08/Jul/2019:22:26:17 +0200] category=CORE severity=NOTICE msgID=203 msg=The Directory Server is now stopped

```
Resource file exists in jar. I've tried building plugin using 2 sources: git and example-plugin.zip file in serwer directory. No differences.
Server has minimal configuration: standalone, enabled only LDAP (1386) and admin connector (4444).

When I try dsconfig (without running server) there is similar exception:
```
~/work/tmp/opendj$ bin/dsconfig -h localhost -p 4444 -D "cn=Directory Manager" -w password create-plugin --plugin-name "example-plugin" --type custom --set enabled:true --set plugin-type:startup -X -n
Exception in thread "main" java.util.MissingResourceException: Can't find resource config/profiles/cli/com/example/opendj/meta/ExamplePluginCfgDefn.properties
	at org.forgerock.opendj.config.ManagedObjectDefinitionResource.getProperties(ManagedObjectDefinitionResource.java:104)
	at org.forgerock.opendj.config.ManagedObjectDefinitionResource.getString(ManagedObjectDefinitionResource.java:77)
	at org.forgerock.opendj.config.dsconfig.CLIProfile.isForCustomization(CLIProfile.java:115)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandler.getShortTypeName(SubCommandHandler.java:1261)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandler.getSubTypes(SubCommandHandler.java:1217)
	at org.forgerock.opendj.config.dsconfig.CreateSubCommandHandler.<init>(CreateSubCommandHandler.java:896)
	at org.forgerock.opendj.config.dsconfig.CreateSubCommandHandler.create(CreateSubCommandHandler.java:317)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory$Visitor.visitInstantiable(SubCommandHandlerFactory.java:52)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory$Visitor.visitInstantiable(SubCommandHandlerFactory.java:45)
	at org.forgerock.opendj.config.InstantiableRelationDefinition.accept(InstantiableRelationDefinition.java:143)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory.processPath(SubCommandHandlerFactory.java:244)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory.processRelation(SubCommandHandlerFactory.java:308)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory.access$1000(SubCommandHandlerFactory.java:40)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory$Visitor.visitSingleton(SubCommandHandlerFactory.java:120)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory$Visitor.visitSingleton(SubCommandHandlerFactory.java:45)
	at org.forgerock.opendj.config.SingletonRelationDefinition.accept(SingletonRelationDefinition.java:99)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory.processPath(SubCommandHandlerFactory.java:244)
	at org.forgerock.opendj.config.dsconfig.SubCommandHandlerFactory.<init>(SubCommandHandlerFactory.java:167)
	at org.forgerock.opendj.config.dsconfig.DSConfig.initializeSubCommands(DSConfig.java:987)
	at org.forgerock.opendj.config.dsconfig.DSConfig.run(DSConfig.java:1057)
	at org.forgerock.opendj.config.dsconfig.DSConfig.main(DSConfig.java:804)
	at org.forgerock.opendj.config.dsconfig.DSConfig.main(DSConfig.java:771)

```
What I'm missing?

**Comment by 13Homer** [comment]
Nobody is using plugins?

**Comment by maximthomas** [comment]
@13Homer, hi you can rebuild OpenDJ from the master branch and retry to deploy plugin.

**Comment by 13Homer** [comment]
Splendid. Plugin is now working like a charm. Thank you!
Sorry for a delay in response, i didn't got a notofication about your answer and I've little bit forgot about this.
